title: My Articles
description: My Personal Stack Problems
author: Sushant Mathur
github: https://github.com/Sushant-M
about: Software Professional currently employed at Ryussi Technologies.
disqus_shortname: Sushant's Blog
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/SushantMathur1"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sushant-mathur-190870ba/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/Sushant-M"

share:
  twitter_username: SushantMathur1
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://sushant.wiki"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
